config/routes.rb
Rails.application.routes.draw do
devise_for :user
  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'
  resources :tweets do
    collection do
      get "question1"
      get "question2"
      get "question3"
      get "question4"
      get "result"
    end
  end
  root 'hello#index'
  resources :songs do
    collection do
      get "search"
  
    end
    member do
      get "album"
      get "artist"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    require 'rspotify'
    RSpotify.authenticate(ENV['SPOTIFY_CLIENT_ID'], ENV['SPOTIFY_SECRET_ID'])
    def index

    end
    
    def link
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  require 'rspotify'
  RSpotify.authenticate(ENV['SPOTIFY_CLIENT_ID'], ENV['SPOTIFY_SECRET_ID'])

  def search
    if params[:search_artist].present?
      @searchartists = RSpotify::Artist.search(params[:search_artist])
    end

    if params[:search_track].present?
      @searchtracks = RSpotify::Track.search(params[:search_track])
    end
  end

  def show
    @track = RSpotify::Track.find(params[:id])
    if @track.album.present?
      @album = RSpotify::Album.find(@track.album.id)
    else
      @album = nil
    end
  end

  def artist
    @artist = RSpotify::Artist.find(params[:id])
  end

  def album
    @album = RSpotify::Album.find(params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!,except: [:index, :show, :result, :question1, :question2, :question3, :question4]
  require 'rspotify'
  RSpotify.authenticate(ENV['SPOTIFY_CLIENT_ID'], ENV['SPOTIFY_SECRET_ID'])
  def index
    @tweets = Tweet.all
  end
  def result
    @tweets = Tweet.all
  end
  def new
    @tweet = Tweet.new
    @track = RSpotify::Track.find(params[:track_id]) if params[:track_id]
  end

  def create
    tweet = Tweet.new(tweet_params)
    tweet.user_id = current_user.id
    if tweet.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy
    redirect_to action: :index
  end

  def question1
  end
  def question2
  end
  def question3
  end
  def question4
  end
  private
  def tweet_params
    params.require(:tweet).permit(:body, :youtube_url, :youtube_url2, :youtube_url3, :artist_name, :album_name, :track_name, :album_image, :preview_url, :artist_id, :album_id, :comment, :result)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def find_youtube_url(youtube_url)
    if youtube_url.include?("https://youtu.be/")
      youtube_url.gsub("https://youtu.be/", "")
    else
      youtube_url.gsub("https://www.youtube.com/watch?v=", "")
    end
  end
end

app/views/hello/index.html.erb
<div class="swiper-container top">
  <div class="swiper-wrapper">
      <div class="swiper-slide">
  <a href="/songs/2ANVost0y2y52ema1E9xAZ/album">
    <img src="https://i.scdn.co/image/ab67616d0000b273de437d960dda1ac0a3586d97" alt="Thriller" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/2UJcKiJxNryhL050F5Z1Fk/album">
    <img src="https://i.scdn.co/image/ab67616d0000b273fbc71c99f9c1296c56dd51b6" alt="Nevermind (Remastered)" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/0ETFjACtuP2ADo6LFhL6HN/album">
    <img src="https://i.scdn.co/image/ab67616d0000b273dc30583ba717007b00cceb25" alt="Abbey Road (Remastered)" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/4xwx0x7k6c5VuThz5qVqmV/album">
    <img src="https://i.scdn.co/image/ab67616d0000b27398260c528e6eec9dd431c1d7" alt="The Velvet Underground & Nico 45th Anniversary" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/29f2cOueckYE8Nc1pkJjrU/album">
    <img src="https://i.scdn.co/image/ab67616d0000b273de0391ae05929bfe0e952f6b" alt="There's a Riot Goin' On" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/75ol9OP8bJaRqzGimpFHDm/album">
    <img src="https://i.scdn.co/image/ab67616d0000b273da7b326bd7ffa7b6b95b0660" alt="In The Court Of The Crimson King (Expanded & Remastered Original Album Mix)" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/0NouBnbXRJKFWzm9LwCW0K/album">
    <img src="https://i.scdn.co/image/ab67616d0000b273b57713d0fe3553a087419f8f" alt="Queen II (2011 Remaster)" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/20r762YmB5HeofjMCiPMLv/album">
    <img src="https://i.scdn.co/image/ab67616d0000b273d9194aa18fa4c9362b47464f" alt="My Beutiful" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/5Y0p2XCgRRIjna91aQE8q7/album">
    <img src="https://i.scdn.co/image/ab67616d0000b273ada101c2e9e97feb8fae37a9" alt="Queen is dead" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/5iIWnMgvSM8uEBwXKsPcXM/album">
    <img src="https://i.scdn.co/image/ab67616d0000b273fbcaf7402f38faac27610efc" alt="Layla" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/0bCAjiUamIFqKJsekOYuRw">
    <img src="https://i.scdn.co/image/ab67616d0000b2731a84d71391df7469c5ab8539" alt="Wish you were here" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/30Perjew8HyGkdSmqguYyg/album">
    <img src="https://i.scdn.co/image/ab67616d0000b273153d79816d853f2694b2cc70" alt="blood suger" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/4m2880jivSbbyEGAKfITCa/album">
    <img src="https://i.scdn.co/image/ab67616d0000b2739b9b36b0e22870b9f542d937" alt="ramdom access" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/50Zz8CkIhATKUlQMbHO3k1/album">
    <img src="https://i.scdn.co/image/ab67616d0000b2736b3fa88bdd4af566fbbf2bbf" alt="whatever?" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/3UsWuvyuXkospeI9nLdVem/album">
    <img src="https://i.scdn.co/image/ab67616d0000b2736f253c0104f24caed5e3e42e" alt="(What's The Story) Morning Glory (Remastered, Deluxe)" class="album-cover">
  </a>
</div>

      

  </div>
</div>

<div class="swiper-container bottom">
  <div class="swiper-wrapper">
      <div class="swiper-slide">
  <a href="/songs/6FCzvataOZh68j8OKzOt9a/album">
    <img src="https://i.scdn.co/image/ab67616d0000b273cd9d8bc9ef04014b6e90e182" alt="London Calling (Remastered)" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/6YUCc2RiXcEKS9ibuZxjt0/album">
    <img src="https://i.scdn.co/image/ab67616d0000b2732fee61bfec596bb6f5447c50" alt="Songs In The Key Of Life" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/2cUpAOlQjV5uSjkWj5bEQY/album">
    <img src="https://i.scdn.co/image/ab67616d0000b273c32e12829fb960100a3257c6" alt="Atom Heart Mother" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/3HZKOk1knxrUU3y5ZIOdbz/album">
    <img src="	https://i.scdn.co/image/ab67616d0000b2735db6dbaca8678527e643a866" alt="Aladdin Sane" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/35UJLpClj5EDrhpNIi4DFg/album">
    <img src="https://i.scdn.co/image/ab67616d0000b2739293c743fa542094336c5e12" alt="Bends" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/3ywVzrwMQ3Kq43N9zBdBQm/album">
    <img src="https://i.scdn.co/image/ab67616d0000b27352573463beeda67fe242cab5" alt="fankadelic" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/5PORx6PL7CdOywSJuGVrnc/album">
    <img src="https://i.scdn.co/image/ab67616d0000b27339180b45808493a1f687c91d" alt="screamadelica" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/2yNaksHgeMQM9Quse463b5/album">
    <img src="https://i.scdn.co/image/ab67616d0000b273a388a3f20d1bf2123249cc79" alt="Is This It?" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/1JvXxLsm0PxlGH4LXzqMGq/album">
    <img src="https://i.scdn.co/image/ab67616d0000b273e49a405217bda217816f7bf5" alt="Remain in Light" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/7KOmuu3cbJQEQYGt3XmLmY/album">
    <img src="https://i.scdn.co/image/ab67616d0000b2737aebbd28dd4cfaca652008b7" alt="Kimono My House" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/7ycBtnsMtyVbbwTfJwRjSP/album">
    <img src="https://i.scdn.co/image/ab67616d0000b273cdb645498cd3d8a2db4d05e1" alt="Top pimp" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/6QaVfG1pHYl1z15ZxkvVDW/album">
    <img src="https://i.scdn.co/image/ab67616d0000b27334ef8f7d06cf2fc2146f420a" alt="Sgt. Pepper's Lonely Hearts Club Band (Remastered)" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/1BZoqf8Zje5nGdwZhOjAtD/album">
    <img src="https://i.scdn.co/image/ab67616d0000b273e08b1250db5f75643f1508c9" alt="The Miseducation of Lauryn Hill" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/5MqyhhHbT13zsloD3uHhlQ//album">
    <img src="https://i.scdn.co/image/ab67616d0000b273fe24dcd263c08c6dd84b6e8c" alt="Who's next" class="album-cover">
  </a>
</div>
<div class="swiper-slide">
  <a href="/songs/5EyIDBAqhnlkAHqvPRwdbX/album">
    <img src="https://i.scdn.co/image/ab67616d0000b2734509204d0860cc0cc67e83dc" alt="Led Zeppelin IV (Remaster)" class="album-cover">
  </a>
</div>

      

  </div>
</div>



<!-- Swiper.js のスクリプト -->
<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js" data-turbo="false"></script>
<script>
  document.addEventListener("turbo:load", function() {
    // 上のスワイパー（右方向に流れる）
    var swiperTop = new Swiper(".swiper-container.top", {
      slidesPerView: 'auto', // スライド数を自動調整
      spaceBetween: 10, // スライド間の間隔
      loop: true,
      speed: 10000, // スピード設定
      autoplay: {
        delay: 0, // 自動再生の遅延なし
        disableOnInteraction: false,
      },
    });

    // 下のスワイパー（左方向に流れる）
    var swiperBottom = new Swiper(".swiper-container.bottom", {
      slidesPerView: 'auto',
      spaceBetween: 10,
      loop: true,
      speed: 10000,
      autoplay: {
        delay: 0,
        disableOnInteraction: false,
        reverseDirection: true, // 逆方向にスライド
      },
    });
  });
</script>




<div class="top-text">
    <div class="explain">
        ここは、新たな音楽と出会うことができる場所です！
        <br>診断では、いくつかの質問に答えるだけで、
        <br>あなたにぴったりの洋楽が見つかります！</br>
    </div>
    <div class="decoration"></div>
    <div class="decoration"></div>
    <div class="decoration"></div>
    <div class="decoration"></div>
    <div class="top-button">
        <a href="/tweets/question1" class="btn btn--moderntop">診断<br>スタート</a>
    </div>

</div>

<div class="top-container">
</div>

<div class="top-container2">
</div>

app/views/hello/link.html.erb
<%= link_to 'トップページ', hello_index_path %>
<%= link_to '一覧表示', tweets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>findyoursound</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <h1>Find Your Sound</h1>
      <div class="header-list">
      <ul>
        <li><%= link_to "HOME", hello_index_path %></li>
        <li><%= link_to "LOGIN",new_user_registration_path %></li>
        <li><%= link_to "MUSIC", search_songs_path %></li>
        <li><%= link_to "診断",question1_tweets_path %></li>
      </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/songs/album.html.erb
<div class="album">
  <% if @album.images.any? %>
    <%= image_tag(@album.images[0]["url"]) %>
  <% end %>
  <h2>トラックリスト</h2>
  <% @album.tracks.each do |track| %>
    <div>
      <h3><%= track.track_number %>：<%= link_to track.name, song_path(track.id) %></h3>
    </div>
  <% end %>
</div>

app/views/songs/artist.html.erb
<div class="artist">
  <h1><%= @artist.name %></h1>
  <p>人気度: <%= @artist.popularity %></p>
  <p>ジャンル: <%= @artist.genres.join(", ") %></p>

  <h2>アルバム</h2>
  <% @artist.albums.each do |album| %>
    <div>
      <h3><%= link_to album.name, album_song_path(album.id) %></h3>
      <% if album.images.any? %>
        <%= image_tag(album.images[0]["url"]) %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/songs/search.html.erb
<div class="search">
  <h3>アーティスト名で検索</h3>
  <%= form_with url: search_songs_path, method: :get, local: true do |form| %>
    <%= form.text_field :search_artist, class: "text-field-custom" %>
    <%= form.submit 'アーティスト名検索', class: "styled-submit-button" %>
  <% end %>


  <h3>楽曲名で検索</h3>
  <%= form_with url: search_songs_path, method: :get, local: true do |form| %>
    <%= form.text_field :search_track, class: "text-field-custom" %>
    <%= form.submit '楽曲名検索', class: "styled-submit-button" %>
  <% end %>

  <h1>検索結果</h1>
  <div>
    <% if @searchartists.present? %>
      <% @searchartists.each do |artist| %>
        <div>
          <h3><%= link_to artist.name, artist_song_path(artist.id) %></h3>
          <% if artist.images.any? %>
            <%= image_tag(artist.images[0]["url"]) %>
          <% end %>
        </div>
      <% end %>
    <% end %>

    <% if @searchtracks.present? %>
      <% @searchtracks.each do |track| %>
        <div>
          <h3><%= link_to track.name, song_path(track.id) %></h3>
          <p>アーティスト: <%= track.artists.map { |artist| link_to artist.name, artist_song_path(artist.id) }.join(", ").html_safe %></p>
          <p>アルバム: <%= link_to track.album.name, album_song_path(track.album.id) %></p>
          <% if track.album.images.any? %>
            <%= image_tag(track.album.images[0]["url"]) %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/songs/show.html.erb
<h1><%= @track.name %></h1>
<p>アーティスト: <%= link_to @track.artists.first.name, artist_song_path(@track.artists.first.id) %></p>
<p>アルバム: <%= link_to @track.album.name, album_song_path(@track.album.id) %></p>
<p>リリース日: <%= @track.album.release_date %></p>
<p>トラック番号: <%= @track.track_number %></p>
<p>長さ: <%= @track.duration_ms / 1000 %> 秒</p>
<% if user_signed_in? %>
  <%= link_to 'この楽曲について投稿する', new_tweet_path(track_id: @track.id) %>
<% end %>
<% if @track.album.images.any? %>
  <%= image_tag(@track.album.images[0]["url"]) %>
<% end %>

app/views/tweets/edit.html.erb
<%= form_for @tweet do |form| %>
    <%= form.label :body %>
    <%= form.text_field :body, :size => 200 %> 
    <div>
    <%= form.label :comment, "コメント" %>
    <%= form.text_area :comment %>
  </div>
  <div>
    <%= form.label :result, "結果" %>
    <%= form.text_field :result %>
  </div>
  <div>
    <%= form.label :youtube_url, "youtube" %>
    <%= form.text_field :youtube_url %>
    <%= form.label :youtube_url2, "youtube" %>
    <%= form.text_field :youtube_url2 %>
    <%= form.label :youtube_url3, "youtube" %>
    <%= form.text_field :youtube_url3 %>
  </div>
    <%= form.submit "編集する" %>
 <% end %>

app/views/tweets/index.html.erb
<h1>GeekTwitter</h1>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<h3>Tweet一覧</h3>
<%= link_to "新規投稿へ", new_tweet_path %>
<div class="tweets-container">
  <% @tweets.each do |t| %>
  <div class="tweet">
    <h2><%= link_to t.track_name, tweet_path(t) %></h2>
    <p>アーティスト: <%= link_to t.artist_name, artist_song_path(t.artist_id) %></p>
    <p>アルバム: <%= link_to t.album_name,     album_song_path(t.album_id)   %></p>
    <p>コメント: <%= t.comment %></p>
    <% if t.album_image.present? %>
      <%= image_tag t.album_image %>
    <% end %>
    <%= link_to "詳細へ", tweet_path(t.id) %>
    <%= link_to "編集する", edit_tweet_path(t.id) %>
    <%= button_to "削除する", tweet_path(t.id), method: :delete %>
    <% if t.youtube_url.present? %>
      <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= find_youtube_url(t.youtube_url) %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <% end %>
  </div>
  <% end %>
</div>

app/views/tweets/new.html.erb
<%= form_with(model: @tweet, local: true) do |form| %>
  <% if @track %>
    <div>
      <p>アーティスト名:<%= @track.artists.first.name %></p>
      <%= form.hidden_field :artist_name, value: @track.artists.first.name, readonly: true %>
      <%= form.hidden_field :artist_id, value: @track.artists.first.id %>
    </div>
    <div>
      <p>アルバム名:<%= @track.album.name %></p>
      <%= form.hidden_field :album_name, value: @track.album.name, readonly: true %>
      <%= form.hidden_field :album_id, value: @track.album.id %>
    </div>
    <div>
      <p>楽曲名:<%= @track.name %></p>
      <%= form.hidden_field :track_name, value: @track.name, readonly: true %>
    </div>
    <div>
      <%= form.hidden_field :album_image, value: @track.album.images.first["url"], readonly: true %>
      <% if @track.album.images.any? %>
        <%= image_tag(@track.album.images.first["url"]) %>
      <% end %>
    </div>
    <div>
      <%= form.hidden_field :preview_url, value: @track.preview_url, readonly: true %>
      <% if @track.preview_url.present? %>
        <audio controls>
          <source src="<%= @track.preview_url %>" type="audio/mpeg">
          Your browser does not support the audio element.
        </audio>
      <% else %>
        <p>プレビューは利用できません。</p>
      <% end %>
    </div>
  <% else %>
    <!-- Optional: Fields for manual entry -->
  <% end %>
  <div>
    <%= form.label :comment, "コメント" %>
    <%= form.text_area :comment %>
  </div>
  <div>
    <%= form.label :result, "結果" %>
    <%= form.text_field :result %>
  </div>
  <div>
    <%= form.label :youtube_url, "youtube" %>
    <%= form.text_field :youtube_url %>
    <%= form.label :youtube_url2, "youtube" %>
    <%= form.text_field :youtube_url2 %>
    <%= form.label :youtube_url3, "youtube" %>
    <%= form.text_field :youtube_url3 %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/question1.html.erb
<div class="decoration"></div>
<div class="decoration"></div>
<div class="decoration"></div>
<div class="decoration"></div>

<div class="question">
  Q1 失敗した時、しばらくそれを思い出しては一人反省会をすることが多い。
</div>

<div class="answer">
  <a href="/tweets/question2?answer=A" class="btn btn--modern">はい</a>
  <a href="/tweets/question2?answer=B" class="btn btn--modern2">いいえ</a>
</div>

app/views/tweets/question2.html.erb
<div class="decoration"></div>
<div class="decoration"></div>
<div class="decoration"></div>
<div class="decoration"></div>
    

<% if params[:answer] == "A" %>

    <div class="question">
      Q2 課題は締切ギリギリなことが多い
    </div>
    <div class="answer">
      <a href="/tweets/question3?answer=C" class="btn btn--modern">はい</a>
      <a href="/tweets/question3?answer=D" class="btn btn--modern2">いいえ</a>
    </div>
<% elsif params[:answer] == "B" %>

    <div class="question">
      Q2 課題は締切ギリギリなことが多い
    </div>
    <div class="answer">
      <a href="/tweets/question3?answer=E" class="btn btn--modern">はい</a>
      <a href="/tweets/question3?answer=F" class="btn btn--modern2">いいえ</a>
    </div>
<% end %>

app/views/tweets/result.html.erb
<div class="recommend">
  "Recommended for You！"
</div>

<div id="tweets">
  <% @tweets.each do |t| %>
    <% if params[:answer] == t.result %>
  <div class="tweet">
    <div class="artist-info">
      <div class="artistname"> 
        <%= link_to t.artist_name, artist_song_path(t.artist_id) %>
      </div>
      <div class="track">
        <%= link_to t.track_name, tweet_path(t) %>
      </div>
      <p1>アルバム: <%= link_to t.album_name,     album_song_path(t.album_id)   %></p>
    </div>
    <div class="content-container">
      <div class="comment"> 
        <p1> <%= t.comment %></p>
        <% if t.album_image.present? %>
          <%= image_tag t.album_image ,class:"albumsize"%>
        <% end %>
        <% if user_signed_in? && current_user.id == t.user_id %>  
          <br>
            <%= link_to "詳細へ", tweet_path(t.id) %>
            <%= link_to "編集する", edit_tweet_path(t.id) %>
            <%= button_to "削除する", tweet_path(t.id), method: :delete %>
          </br>
        <% end %>  
      </div>
      <div class="video-container">
        <% if t.youtube_url.present? %>
          <iframe width="480" height="340" src="https://www.youtube.com/embed/<%= find_youtube_url(t.youtube_url) %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <% end %>
      </div>
      <div class="video-container2">
        <% if t.youtube_url2.present? %>
          <iframe width="280" height="160" src="https://www.youtube.com/embed/<%= find_youtube_url(t.youtube_url2) %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <% end %>
        <% if t.youtube_url3.present? %>
          <iframe width="280" height="160" src="https://www.youtube.com/embed/<%= find_youtube_url(t.youtube_url3) %>" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <% end %>
      </div>
    </div>
  </div>
    <% end %>
  <% end %>
</div>

app/views/tweets/show.html.erb
<h1>投稿</h1>
<h3>Tweet詳細</h3>
<div class="tweet">
  <p><%= @tweet.body %></p>
  <p><%= @tweet.created_at %></p>
</div>

<%= link_to "Tweet一覧に戻る", tweets_path %>
<%= link_to "編集する", edit_tweet_path(@tweet.id) %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>